### ISSUE TITLE
Implement caching to speed up the build and save some trees

### ISSUE THREAD

**Issue by shonderdos** [shonderdos/labs#580]
```
steps:
- uses: actions/checkout@v4
- uses: actions/setup-node@v3
  with:
    node-version: 16
    cache: 'npm'
    cache-dependency-path: subdir/package-lock.json
- run: npm ci
- run: npm test
 ```

https://github.com/actions/setup-node#caching-global-packages-data
